name: Build and Upload Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/sniffl-amd64.exe .
          GOOS=linux GOARCH=amd64 go build -o dist/sniffl-linux-amd64 .
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o dist/sniffl-mac-arm64 .

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
